### YamlMime:ManagedReference
items:
- uid: MyProject.ExploreGame.Application.ExploreJoinCommand
  commentId: T:MyProject.ExploreGame.Application.ExploreJoinCommand
  id: ExploreJoinCommand
  parent: MyProject.ExploreGame.Application
  children:
  - MyProject.ExploreGame.Application.ExploreJoinCommand.#ctor(System.Int64,System.String)
  - MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName
  langs:
  - csharp
  - vb
  name: ExploreJoinCommand
  nameWithType: ExploreJoinCommand
  fullName: MyProject.ExploreGame.Application.ExploreJoinCommand
  type: Class
  namespace: MyProject.ExploreGame.Application
  summary: 게임 참가 커맨드입니다.
  example: []
  syntax:
    content: 'public sealed class ExploreJoinCommand : ExploreCommand'
    content.vb: Public NotInheritable Class ExploreJoinCommand Inherits ExploreCommand
  inheritance:
  - System.Object
  - MyProject.Common.Host.GameCommandBase
  - MyProject.ExploreGame.Application.ExploreCommand
  inheritedMembers:
  - MyProject.Common.Host.GameCommandBase.CommandId
  - MyProject.Common.Host.GameCommandBase.SenderUid
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName
  commentId: P:MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName
  id: CharacterName
  parent: MyProject.ExploreGame.Application.ExploreJoinCommand
  langs:
  - csharp
  - vb
  name: CharacterName
  nameWithType: ExploreJoinCommand.CharacterName
  fullName: MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName
  type: Property
  namespace: MyProject.ExploreGame.Application
  syntax:
    content: public string CharacterName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property CharacterName As String
  overload: MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName*
- uid: MyProject.ExploreGame.Application.ExploreJoinCommand.#ctor(System.Int64,System.String)
  commentId: M:MyProject.ExploreGame.Application.ExploreJoinCommand.#ctor(System.Int64,System.String)
  id: '#ctor(System.Int64,System.String)'
  parent: MyProject.ExploreGame.Application.ExploreJoinCommand
  langs:
  - csharp
  - vb
  name: ExploreJoinCommand(long, string)
  nameWithType: ExploreJoinCommand.ExploreJoinCommand(long, string)
  fullName: MyProject.ExploreGame.Application.ExploreJoinCommand.ExploreJoinCommand(long, string)
  type: Constructor
  namespace: MyProject.ExploreGame.Application
  syntax:
    content: public ExploreJoinCommand(long senderUid, string characterName)
    parameters:
    - id: senderUid
      type: System.Int64
    - id: characterName
      type: System.String
    content.vb: Public Sub New(senderUid As Long, characterName As String)
  overload: MyProject.ExploreGame.Application.ExploreJoinCommand.#ctor*
  nameWithType.vb: ExploreJoinCommand.New(Long, String)
  fullName.vb: MyProject.ExploreGame.Application.ExploreJoinCommand.New(Long, String)
  name.vb: New(Long, String)
references:
- uid: MyProject.ExploreGame.Application
  commentId: N:MyProject.ExploreGame.Application
  href: MyProject.html
  name: MyProject.ExploreGame.Application
  nameWithType: MyProject.ExploreGame.Application
  fullName: MyProject.ExploreGame.Application
  spec.csharp:
  - uid: MyProject
    name: MyProject
    href: MyProject.html
  - name: .
  - uid: MyProject.ExploreGame
    name: ExploreGame
    href: MyProject.ExploreGame.html
  - name: .
  - uid: MyProject.ExploreGame.Application
    name: Application
    href: MyProject.ExploreGame.Application.html
  spec.vb:
  - uid: MyProject
    name: MyProject
    href: MyProject.html
  - name: .
  - uid: MyProject.ExploreGame
    name: ExploreGame
    href: MyProject.ExploreGame.html
  - name: .
  - uid: MyProject.ExploreGame.Application
    name: Application
    href: MyProject.ExploreGame.Application.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MyProject.Common.Host.GameCommandBase
  commentId: T:MyProject.Common.Host.GameCommandBase
  parent: MyProject.Common.Host
  href: MyProject.Common.Host.GameCommandBase.html
  name: GameCommandBase
  nameWithType: GameCommandBase
  fullName: MyProject.Common.Host.GameCommandBase
- uid: MyProject.ExploreGame.Application.ExploreCommand
  commentId: T:MyProject.ExploreGame.Application.ExploreCommand
  parent: MyProject.ExploreGame.Application
  href: MyProject.ExploreGame.Application.ExploreCommand.html
  name: ExploreCommand
  nameWithType: ExploreCommand
  fullName: MyProject.ExploreGame.Application.ExploreCommand
- uid: MyProject.Common.Host.GameCommandBase.CommandId
  commentId: P:MyProject.Common.Host.GameCommandBase.CommandId
  parent: MyProject.Common.Host.GameCommandBase
  href: MyProject.Common.Host.GameCommandBase.html#MyProject_Common_Host_GameCommandBase_CommandId
  name: CommandId
  nameWithType: GameCommandBase.CommandId
  fullName: MyProject.Common.Host.GameCommandBase.CommandId
- uid: MyProject.Common.Host.GameCommandBase.SenderUid
  commentId: P:MyProject.Common.Host.GameCommandBase.SenderUid
  parent: MyProject.Common.Host.GameCommandBase
  href: MyProject.Common.Host.GameCommandBase.html#MyProject_Common_Host_GameCommandBase_SenderUid
  name: SenderUid
  nameWithType: GameCommandBase.SenderUid
  fullName: MyProject.Common.Host.GameCommandBase.SenderUid
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MyProject.Common.Host
  commentId: N:MyProject.Common.Host
  href: MyProject.html
  name: MyProject.Common.Host
  nameWithType: MyProject.Common.Host
  fullName: MyProject.Common.Host
  spec.csharp:
  - uid: MyProject
    name: MyProject
    href: MyProject.html
  - name: .
  - uid: MyProject.Common
    name: Common
    href: MyProject.Common.html
  - name: .
  - uid: MyProject.Common.Host
    name: Host
    href: MyProject.Common.Host.html
  spec.vb:
  - uid: MyProject
    name: MyProject
    href: MyProject.html
  - name: .
  - uid: MyProject.Common
    name: Common
    href: MyProject.Common.html
  - name: .
  - uid: MyProject.Common.Host
    name: Host
    href: MyProject.Common.Host.html
- uid: MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName*
  commentId: Overload:MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName
  href: MyProject.ExploreGame.Application.ExploreJoinCommand.html#MyProject_ExploreGame_Application_ExploreJoinCommand_CharacterName
  name: CharacterName
  nameWithType: ExploreJoinCommand.CharacterName
  fullName: MyProject.ExploreGame.Application.ExploreJoinCommand.CharacterName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MyProject.ExploreGame.Application.ExploreJoinCommand.#ctor*
  commentId: Overload:MyProject.ExploreGame.Application.ExploreJoinCommand.#ctor
  href: MyProject.ExploreGame.Application.ExploreJoinCommand.html#MyProject_ExploreGame_Application_ExploreJoinCommand__ctor_System_Int64_System_String_
  name: ExploreJoinCommand
  nameWithType: ExploreJoinCommand.ExploreJoinCommand
  fullName: MyProject.ExploreGame.Application.ExploreJoinCommand.ExploreJoinCommand
  nameWithType.vb: ExploreJoinCommand.New
  fullName.vb: MyProject.ExploreGame.Application.ExploreJoinCommand.New
  name.vb: New
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
