### YamlMime:ManagedReference
items:
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent
  commentId: T:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent
  id: DefenseAbilitySelectedEvent
  parent: MyProject.DefenseGame.Application
  children:
  - MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.#ctor(System.Int64,Noname.GameAbilitySystem.Domain.FGameplayTag,System.String)
  - MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName
  - MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag
  langs:
  - csharp
  - vb
  name: DefenseAbilitySelectedEvent
  nameWithType: DefenseAbilitySelectedEvent
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent
  type: Class
  assemblies:
  - Assembly-CSharp
  namespace: MyProject.DefenseGame.Application
  summary: 어빌리티 선택 완료 이벤트입니다.
  example: []
  syntax:
    content: 'public sealed class DefenseAbilitySelectedEvent : DefenseHostEvent'
    content.vb: Public NotInheritable Class DefenseAbilitySelectedEvent Inherits DefenseHostEvent
  inheritance:
  - System.Object
  - Noname.GameHost.GameEventBase
  - MyProject.DefenseGame.Application.DefenseHostEvent
  inheritedMembers:
  - Noname.GameHost.GameEventBase.Tick
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag
  commentId: P:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag
  id: AbilityTag
  parent: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent
  langs:
  - csharp
  - vb
  name: AbilityTag
  nameWithType: DefenseAbilitySelectedEvent.AbilityTag
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag
  type: Property
  assemblies:
  - Assembly-CSharp
  namespace: MyProject.DefenseGame.Application
  syntax:
    content: public FGameplayTag AbilityTag { get; }
    parameters: []
    return:
      type: Noname.GameAbilitySystem.Domain.FGameplayTag
    content.vb: Public ReadOnly Property AbilityTag As FGameplayTag
  overload: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag*
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName
  commentId: P:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName
  id: AbilityName
  parent: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent
  langs:
  - csharp
  - vb
  name: AbilityName
  nameWithType: DefenseAbilitySelectedEvent.AbilityName
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName
  type: Property
  assemblies:
  - Assembly-CSharp
  namespace: MyProject.DefenseGame.Application
  syntax:
    content: public string AbilityName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property AbilityName As String
  overload: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName*
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.#ctor(System.Int64,Noname.GameAbilitySystem.Domain.FGameplayTag,System.String)
  commentId: M:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.#ctor(System.Int64,Noname.GameAbilitySystem.Domain.FGameplayTag,System.String)
  id: '#ctor(System.Int64,Noname.GameAbilitySystem.Domain.FGameplayTag,System.String)'
  parent: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent
  langs:
  - csharp
  - vb
  name: DefenseAbilitySelectedEvent(long, FGameplayTag, string)
  nameWithType: DefenseAbilitySelectedEvent.DefenseAbilitySelectedEvent(long, FGameplayTag, string)
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.DefenseAbilitySelectedEvent(long, Noname.GameAbilitySystem.Domain.FGameplayTag, string)
  type: Constructor
  assemblies:
  - Assembly-CSharp
  namespace: MyProject.DefenseGame.Application
  syntax:
    content: public DefenseAbilitySelectedEvent(long tick, FGameplayTag abilityTag, string abilityName)
    parameters:
    - id: tick
      type: System.Int64
    - id: abilityTag
      type: Noname.GameAbilitySystem.Domain.FGameplayTag
    - id: abilityName
      type: System.String
    content.vb: Public Sub New(tick As Long, abilityTag As FGameplayTag, abilityName As String)
  overload: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.#ctor*
  nameWithType.vb: DefenseAbilitySelectedEvent.New(Long, FGameplayTag, String)
  fullName.vb: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.New(Long, Noname.GameAbilitySystem.Domain.FGameplayTag, String)
  name.vb: New(Long, FGameplayTag, String)
references:
- uid: MyProject.DefenseGame.Application
  commentId: N:MyProject.DefenseGame.Application
  href: MyProject.html
  name: MyProject.DefenseGame.Application
  nameWithType: MyProject.DefenseGame.Application
  fullName: MyProject.DefenseGame.Application
  spec.csharp:
  - uid: MyProject
    name: MyProject
    href: MyProject.html
  - name: .
  - uid: MyProject.DefenseGame
    name: DefenseGame
    href: MyProject.DefenseGame.html
  - name: .
  - uid: MyProject.DefenseGame.Application
    name: Application
    href: MyProject.DefenseGame.Application.html
  spec.vb:
  - uid: MyProject
    name: MyProject
    href: MyProject.html
  - name: .
  - uid: MyProject.DefenseGame
    name: DefenseGame
    href: MyProject.DefenseGame.html
  - name: .
  - uid: MyProject.DefenseGame.Application
    name: Application
    href: MyProject.DefenseGame.Application.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Noname.GameHost.GameEventBase
  commentId: T:Noname.GameHost.GameEventBase
  parent: Noname.GameHost
  name: GameEventBase
  nameWithType: GameEventBase
  fullName: Noname.GameHost.GameEventBase
- uid: MyProject.DefenseGame.Application.DefenseHostEvent
  commentId: T:MyProject.DefenseGame.Application.DefenseHostEvent
  parent: MyProject.DefenseGame.Application
  href: MyProject.DefenseGame.Application.DefenseHostEvent.html
  name: DefenseHostEvent
  nameWithType: DefenseHostEvent
  fullName: MyProject.DefenseGame.Application.DefenseHostEvent
- uid: Noname.GameHost.GameEventBase.Tick
  commentId: P:Noname.GameHost.GameEventBase.Tick
  parent: Noname.GameHost.GameEventBase
  name: Tick
  nameWithType: GameEventBase.Tick
  fullName: Noname.GameHost.GameEventBase.Tick
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Noname.GameHost
  commentId: N:Noname.GameHost
  name: Noname.GameHost
  nameWithType: Noname.GameHost
  fullName: Noname.GameHost
  spec.csharp:
  - uid: Noname
    name: Noname
  - name: .
  - uid: Noname.GameHost
    name: GameHost
  spec.vb:
  - uid: Noname
    name: Noname
  - name: .
  - uid: Noname.GameHost
    name: GameHost
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag*
  commentId: Overload:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag
  href: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.html#MyProject_DefenseGame_Application_DefenseAbilitySelectedEvent_AbilityTag
  name: AbilityTag
  nameWithType: DefenseAbilitySelectedEvent.AbilityTag
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityTag
- uid: Noname.GameAbilitySystem.Domain.FGameplayTag
  commentId: T:Noname.GameAbilitySystem.Domain.FGameplayTag
  parent: Noname.GameAbilitySystem.Domain
  name: FGameplayTag
  nameWithType: FGameplayTag
  fullName: Noname.GameAbilitySystem.Domain.FGameplayTag
- uid: Noname.GameAbilitySystem.Domain
  commentId: N:Noname.GameAbilitySystem.Domain
  name: Noname.GameAbilitySystem.Domain
  nameWithType: Noname.GameAbilitySystem.Domain
  fullName: Noname.GameAbilitySystem.Domain
  spec.csharp:
  - uid: Noname
    name: Noname
  - name: .
  - uid: Noname.GameAbilitySystem
    name: GameAbilitySystem
  - name: .
  - uid: Noname.GameAbilitySystem.Domain
    name: Domain
  spec.vb:
  - uid: Noname
    name: Noname
  - name: .
  - uid: Noname.GameAbilitySystem
    name: GameAbilitySystem
  - name: .
  - uid: Noname.GameAbilitySystem.Domain
    name: Domain
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName*
  commentId: Overload:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName
  href: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.html#MyProject_DefenseGame_Application_DefenseAbilitySelectedEvent_AbilityName
  name: AbilityName
  nameWithType: DefenseAbilitySelectedEvent.AbilityName
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.AbilityName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.#ctor*
  commentId: Overload:MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.#ctor
  href: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.html#MyProject_DefenseGame_Application_DefenseAbilitySelectedEvent__ctor_System_Int64_Noname_GameAbilitySystem_Domain_FGameplayTag_System_String_
  name: DefenseAbilitySelectedEvent
  nameWithType: DefenseAbilitySelectedEvent.DefenseAbilitySelectedEvent
  fullName: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.DefenseAbilitySelectedEvent
  nameWithType.vb: DefenseAbilitySelectedEvent.New
  fullName.vb: MyProject.DefenseGame.Application.DefenseAbilitySelectedEvent.New
  name.vb: New
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
